config/routes.rb
Rails.application.routes.draw do
  root "products#index"
    get "/products", to: "products#index"
    get '/products/:id/buy', to: 'products#buy', as: 'buy'
    get '/cart', to: 'products#cart', as: 'cart'
    get "products.json", to: "products#list"
    get '/order', to: 'products#order', as: 'order'
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord

validates :title, presence: true
validates :price, comparison: {greater_than:0}


end

app/models/product_updated.rb
class ProductUpdated < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    if session[:cart].nil?
      session[:cart] = []
    end
    @cart = session[:cart]
  end

  def show
  @product = Product.find(params[:id])
  end

  def buy


  if session[:cart].nil?
    session[:cart] = []
  end
  @product = Product.find(params[:id])
  session[:cart].append(@product)
  redirect_to :root
  end
  def cart
  @cart = session[:cart]
  #session[:cart] = []
  end

  def list
    #return products as json list
    @products = Product.all
    render json: @products
  end




  def order
  @cart = session[:cart]
  @cart.each do |item|
    p=Product.find(item["id"])
    p.quantity = p.quantity-1
    p.save
  end
  session[:cart] = []
  end


  private
  def product_params
  params.require(:product).permit(:title, :price, :image, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/cart.html.erb
<h1>Your Cart!<h1>

<ul>
<% @cart.each do |product| %>
<ul class="list-group">
    <li class="list-group-item"> <%=product["title"]%> </li>
</ul>
<%end%>
<%=@cart.length%> items in your cart
<ul>
<a class= "btn btn-primary" href="/">Keep Shopping</a>
<a class= "btn btn-primary" href="/order">Order Now!</a>

app/views/products/index.html.erb
<div class= "container">
    <h1>MID-MERCH</h1>


    <hr/>
    <div class="alert alert-primary" role="alert">
    <%=@cart.length%> items in your cart
    </div>
    <hr/>


    <% @products.each do |product| %>
    <div class="row row-cols-3">
        <ul class="list-group">
            <li class="list-group-item"><strong><%=product.title%></strong>:</li>
            <li class="list-group-item"><%= image_tag(product.image, width: 200)%></li>
            <li class="list-group-item"><%=product.description%></li>
            <li class="list-group-item">Costs $<%=product.price%> dollars</li>
            <li class="list-group-item"><%=product.quantity%> left!</li>
            <li class="list-group-item"><%= link_to "Buy Now", buy_path(product), class: "btn btn-primary" %></li>
    
        </ul>
    </div>
    <hr/>
    <%end%>
    <hr/>
    <strong>

    <a class= "btn btn-primary" href="/cart">Checkout</a>
</div>

app/views/products/order.html.erb
<h1> Your order has shipped!!<h1>
<a class= "btn btn-success" href="/">Keep Shopping</a>